/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Escrow {
  export type OrderStruct = {
    buyer: AddressLike;
    vendor: AddressLike;
    reseller: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    depositedAt: BigNumberish;
    deliveredAt: BigNumberish;
    releasedAt: BigNumberish;
    refundReason: string;
  };

  export type OrderStructOutput = [
    buyer: string,
    vendor: string,
    reseller: string,
    amount: bigint,
    status: bigint,
    depositedAt: bigint,
    deliveredAt: bigint,
    releasedAt: bigint,
    refundReason: string
  ] & {
    buyer: string;
    vendor: string;
    reseller: string;
    amount: bigint;
    status: bigint;
    depositedAt: bigint;
    deliveredAt: bigint;
    releasedAt: bigint;
    refundReason: string;
  };
}

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmDelivery"
      | "deposit"
      | "dispute"
      | "getOrder"
      | "getOrderStatus"
      | "minOrderAmount"
      | "orders"
      | "owner"
      | "referralRegistry"
      | "refund"
      | "release"
      | "renounceOwnership"
      | "reputation"
      | "setMinOrderAmount"
      | "splitPayout"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryConfirmed"
      | "DisputeOpened"
      | "EscrowDeposited"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "MinOrderAmountUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmDelivery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getOrderStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minOrderAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referralRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinOrderAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "splitPayout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minOrderAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinOrderAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "splitPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeOpenedEvent {
  export type InputTuple = [orderId: BytesLike, initiator: AddressLike];
  export type OutputTuple = [orderId: string, initiator: string];
  export interface OutputObject {
    orderId: string;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowDepositedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    buyer: AddressLike,
    vendor: AddressLike,
    reseller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    buyer: string,
    vendor: string,
    reseller: string,
    amount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    vendor: string;
    reseller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    buyer: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    orderId: string,
    buyer: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [orderId: BytesLike, releaseAmount: BigNumberish];
  export type OutputTuple = [orderId: string, releaseAmount: bigint];
  export interface OutputObject {
    orderId: string;
    releaseAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinOrderAmountUpdatedEvent {
  export type InputTuple = [newAmount: BigNumberish];
  export type OutputTuple = [newAmount: bigint];
  export interface OutputObject {
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmDelivery: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [orderId: BytesLike, vendor: AddressLike, reseller: AddressLike],
    [void],
    "payable"
  >;

  dispute: TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [Escrow.OrderStructOutput],
    "view"
  >;

  getOrderStatus: TypedContractMethod<[orderId: BytesLike], [bigint], "view">;

  minOrderAmount: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        buyer: string;
        vendor: string;
        reseller: string;
        amount: bigint;
        status: bigint;
        depositedAt: bigint;
        deliveredAt: bigint;
        releasedAt: bigint;
        refundReason: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  referralRegistry: TypedContractMethod<[], [string], "view">;

  refund: TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  release: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[], [string], "view">;

  setMinOrderAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  splitPayout: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmDelivery"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [orderId: BytesLike, vendor: AddressLike, reseller: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [Escrow.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderStatus"
  ): TypedContractMethod<[orderId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "minOrderAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        buyer: string;
        vendor: string;
        reseller: string;
        amount: bigint;
        status: bigint;
        depositedAt: bigint;
        deliveredAt: bigint;
        releasedAt: bigint;
        refundReason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<
    [orderId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMinOrderAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "splitPayout"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeOpened"
  ): TypedContractEvent<
    DisputeOpenedEvent.InputTuple,
    DisputeOpenedEvent.OutputTuple,
    DisputeOpenedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowDeposited"
  ): TypedContractEvent<
    EscrowDepositedEvent.InputTuple,
    EscrowDepositedEvent.OutputTuple,
    EscrowDepositedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MinOrderAmountUpdated"
  ): TypedContractEvent<
    MinOrderAmountUpdatedEvent.InputTuple,
    MinOrderAmountUpdatedEvent.OutputTuple,
    MinOrderAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DeliveryConfirmed(bytes32)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "DisputeOpened(bytes32,address)": TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;
    DisputeOpened: TypedContractEvent<
      DisputeOpenedEvent.InputTuple,
      DisputeOpenedEvent.OutputTuple,
      DisputeOpenedEvent.OutputObject
    >;

    "EscrowDeposited(bytes32,address,address,address,uint256)": TypedContractEvent<
      EscrowDepositedEvent.InputTuple,
      EscrowDepositedEvent.OutputTuple,
      EscrowDepositedEvent.OutputObject
    >;
    EscrowDeposited: TypedContractEvent<
      EscrowDepositedEvent.InputTuple,
      EscrowDepositedEvent.OutputTuple,
      EscrowDepositedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address,uint256,string)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "MinOrderAmountUpdated(uint256)": TypedContractEvent<
      MinOrderAmountUpdatedEvent.InputTuple,
      MinOrderAmountUpdatedEvent.OutputTuple,
      MinOrderAmountUpdatedEvent.OutputObject
    >;
    MinOrderAmountUpdated: TypedContractEvent<
      MinOrderAmountUpdatedEvent.InputTuple,
      MinOrderAmountUpdatedEvent.OutputTuple,
      MinOrderAmountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
