/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReferralRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReferralChain"
      | "getReferralCount"
      | "getReferrer"
      | "isRegistered"
      | "maxChainDepth"
      | "owner"
      | "referralCounts"
      | "referrers"
      | "registerReferral"
      | "registered"
      | "renounceOwnership"
      | "setMaxChainDepth"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxChainDepthUpdated"
      | "OwnershipTransferred"
      | "ReferralRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getReferralChain",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferralCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReferrer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxChainDepth",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referralCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "referrers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerReferral",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxChainDepth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReferralChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferralCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxChainDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referrers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxChainDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MaxChainDepthUpdatedEvent {
  export type InputTuple = [newDepth: BigNumberish];
  export type OutputTuple = [newDepth: bigint];
  export interface OutputObject {
    newDepth: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralRegisteredEvent {
  export type InputTuple = [referrer: AddressLike, referree: AddressLike];
  export type OutputTuple = [referrer: string, referree: string];
  export interface OutputObject {
    referrer: string;
    referree: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReferralRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReferralRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReferralRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReferralChain: TypedContractMethod<
    [account: AddressLike],
    [string[]],
    "view"
  >;

  getReferralCount: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getReferrer: TypedContractMethod<[account: AddressLike], [string], "view">;

  isRegistered: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  maxChainDepth: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referralCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  referrers: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerReferral: TypedContractMethod<
    [referrer: AddressLike, referree: AddressLike],
    [void],
    "nonpayable"
  >;

  registered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxChainDepth: TypedContractMethod<
    [depth: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReferralChain"
  ): TypedContractMethod<[account: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReferralCount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReferrer"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxChainDepth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "referrers"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerReferral"
  ): TypedContractMethod<
    [referrer: AddressLike, referree: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxChainDepth"
  ): TypedContractMethod<[depth: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MaxChainDepthUpdated"
  ): TypedContractEvent<
    MaxChainDepthUpdatedEvent.InputTuple,
    MaxChainDepthUpdatedEvent.OutputTuple,
    MaxChainDepthUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReferralRegistered"
  ): TypedContractEvent<
    ReferralRegisteredEvent.InputTuple,
    ReferralRegisteredEvent.OutputTuple,
    ReferralRegisteredEvent.OutputObject
  >;

  filters: {
    "MaxChainDepthUpdated(uint256)": TypedContractEvent<
      MaxChainDepthUpdatedEvent.InputTuple,
      MaxChainDepthUpdatedEvent.OutputTuple,
      MaxChainDepthUpdatedEvent.OutputObject
    >;
    MaxChainDepthUpdated: TypedContractEvent<
      MaxChainDepthUpdatedEvent.InputTuple,
      MaxChainDepthUpdatedEvent.OutputTuple,
      MaxChainDepthUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReferralRegistered(address,address)": TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;
    ReferralRegistered: TypedContractEvent<
      ReferralRegisteredEvent.InputTuple,
      ReferralRegisteredEvent.OutputTuple,
      ReferralRegisteredEvent.OutputObject
    >;
  };
}
