/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Reputation {
  export type ReputationEntryStruct = {
    delta: BigNumberish;
    reason: string;
    timestamp: BigNumberish;
  };

  export type ReputationEntryStructOutput = [
    delta: bigint,
    reason: string,
    timestamp: bigint
  ] & { delta: bigint; reason: string; timestamp: bigint };
}

export interface ReputationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditLog"
      | "authorizedCallers"
      | "creditReputation"
      | "debitReputation"
      | "getAuditLogEntry"
      | "getAuditLogLength"
      | "getReputation"
      | "isGenuine"
      | "maxReputationCap"
      | "minReputationThreshold"
      | "owner"
      | "renounceOwnership"
      | "reputation"
      | "setAuthorized"
      | "setMinReputationThreshold"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizationChanged"
      | "GenuinessStatusChanged"
      | "OwnershipTransferred"
      | "ReputationCredited"
      | "ReputationDebited"
      | "ThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "auditLog",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creditReputation",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "debitReputation",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGenuine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxReputationCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minReputationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorized",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinReputationThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "auditLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debitReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGenuine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxReputationCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minReputationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinReputationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuthorizationChangedEvent {
  export type InputTuple = [caller: AddressLike, authorized: boolean];
  export type OutputTuple = [caller: string, authorized: boolean];
  export interface OutputObject {
    caller: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GenuinessStatusChangedEvent {
  export type InputTuple = [vendor: AddressLike, isGenuine: boolean];
  export type OutputTuple = [vendor: string, isGenuine: boolean];
  export interface OutputObject {
    vendor: string;
    isGenuine: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationCreditedEvent {
  export type InputTuple = [
    vendor: AddressLike,
    amount: BigNumberish,
    reason: string,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    vendor: string,
    amount: bigint,
    reason: string,
    newScore: bigint
  ];
  export interface OutputObject {
    vendor: string;
    amount: bigint;
    reason: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationDebitedEvent {
  export type InputTuple = [
    vendor: AddressLike,
    amount: BigNumberish,
    reason: string,
    newScore: BigNumberish
  ];
  export type OutputTuple = [
    vendor: string,
    amount: bigint,
    reason: string,
    newScore: bigint
  ];
  export interface OutputObject {
    vendor: string;
    amount: bigint;
    reason: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Reputation extends BaseContract {
  connect(runner?: ContractRunner | null): Reputation;
  waitForDeployment(): Promise<this>;

  interface: ReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditLog: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint] & {
        delta: bigint;
        reason: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  creditReputation: TypedContractMethod<
    [vendor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  debitReputation: TypedContractMethod<
    [vendor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  getAuditLogEntry: TypedContractMethod<
    [vendor: AddressLike, index: BigNumberish],
    [Reputation.ReputationEntryStructOutput],
    "view"
  >;

  getAuditLogLength: TypedContractMethod<
    [vendor: AddressLike],
    [bigint],
    "view"
  >;

  getReputation: TypedContractMethod<[vendor: AddressLike], [bigint], "view">;

  isGenuine: TypedContractMethod<[vendor: AddressLike], [boolean], "view">;

  maxReputationCap: TypedContractMethod<[], [bigint], "view">;

  minReputationThreshold: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setAuthorized: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  setMinReputationThreshold: TypedContractMethod<
    [threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditLog"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, bigint] & {
        delta: bigint;
        reason: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "creditReputation"
  ): TypedContractMethod<
    [vendor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debitReputation"
  ): TypedContractMethod<
    [vendor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuditLogEntry"
  ): TypedContractMethod<
    [vendor: AddressLike, index: BigNumberish],
    [Reputation.ReputationEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditLogLength"
  ): TypedContractMethod<[vendor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<[vendor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isGenuine"
  ): TypedContractMethod<[vendor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxReputationCap"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minReputationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAuthorized"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinReputationThreshold"
  ): TypedContractMethod<[threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuthorizationChanged"
  ): TypedContractEvent<
    AuthorizationChangedEvent.InputTuple,
    AuthorizationChangedEvent.OutputTuple,
    AuthorizationChangedEvent.OutputObject
  >;
  getEvent(
    key: "GenuinessStatusChanged"
  ): TypedContractEvent<
    GenuinessStatusChangedEvent.InputTuple,
    GenuinessStatusChangedEvent.OutputTuple,
    GenuinessStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationCredited"
  ): TypedContractEvent<
    ReputationCreditedEvent.InputTuple,
    ReputationCreditedEvent.OutputTuple,
    ReputationCreditedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationDebited"
  ): TypedContractEvent<
    ReputationDebitedEvent.InputTuple,
    ReputationDebitedEvent.OutputTuple,
    ReputationDebitedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "AuthorizationChanged(address,bool)": TypedContractEvent<
      AuthorizationChangedEvent.InputTuple,
      AuthorizationChangedEvent.OutputTuple,
      AuthorizationChangedEvent.OutputObject
    >;
    AuthorizationChanged: TypedContractEvent<
      AuthorizationChangedEvent.InputTuple,
      AuthorizationChangedEvent.OutputTuple,
      AuthorizationChangedEvent.OutputObject
    >;

    "GenuinessStatusChanged(address,bool)": TypedContractEvent<
      GenuinessStatusChangedEvent.InputTuple,
      GenuinessStatusChangedEvent.OutputTuple,
      GenuinessStatusChangedEvent.OutputObject
    >;
    GenuinessStatusChanged: TypedContractEvent<
      GenuinessStatusChangedEvent.InputTuple,
      GenuinessStatusChangedEvent.OutputTuple,
      GenuinessStatusChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationCredited(address,uint256,string,int256)": TypedContractEvent<
      ReputationCreditedEvent.InputTuple,
      ReputationCreditedEvent.OutputTuple,
      ReputationCreditedEvent.OutputObject
    >;
    ReputationCredited: TypedContractEvent<
      ReputationCreditedEvent.InputTuple,
      ReputationCreditedEvent.OutputTuple,
      ReputationCreditedEvent.OutputObject
    >;

    "ReputationDebited(address,uint256,string,int256)": TypedContractEvent<
      ReputationDebitedEvent.InputTuple,
      ReputationDebitedEvent.OutputTuple,
      ReputationDebitedEvent.OutputObject
    >;
    ReputationDebited: TypedContractEvent<
      ReputationDebitedEvent.InputTuple,
      ReputationDebitedEvent.OutputTuple,
      ReputationDebitedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
  };
}
