/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SplitPayout {
  export type SplitStruct = {
    reseller: AddressLike;
    vendor: AddressLike;
    amount: BigNumberish;
    resalePayout: BigNumberish;
    vendorPayout: BigNumberish;
    referralPayouts: BigNumberish[];
    treasuryPayout: BigNumberish;
    executed: boolean;
  };

  export type SplitStructOutput = [
    reseller: string,
    vendor: string,
    amount: bigint,
    resalePayout: bigint,
    vendorPayout: bigint,
    referralPayouts: bigint[],
    treasuryPayout: bigint,
    executed: boolean
  ] & {
    reseller: string;
    vendor: string;
    amount: bigint;
    resalePayout: bigint;
    vendorPayout: bigint;
    referralPayouts: bigint[];
    treasuryPayout: bigint;
    executed: boolean;
  };
}

export interface SplitPayoutInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "escrowContract"
      | "getSplit"
      | "maxReferralDepth"
      | "owner"
      | "referralBps"
      | "referralRegistry"
      | "renounceOwnership"
      | "reputation"
      | "resaleMarginBps"
      | "setConfig"
      | "setEscrowContract"
      | "split"
      | "splits"
      | "transferOwnership"
      | "treasuryAddress"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfigUpdated"
      | "OwnershipTransferred"
      | "PaymentSent"
      | "SplitExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "escrowContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getSplit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "maxReferralDepth",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "referralBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referralRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resaleMarginBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "split",
    values: [BytesLike, BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "splits", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "escrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSplit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxReferralDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referralBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "referralRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resaleMarginBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "split", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "splits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [
    resaleMarginBps: BigNumberish,
    referralBps: BigNumberish
  ];
  export type OutputTuple = [resaleMarginBps: bigint, referralBps: bigint];
  export interface OutputObject {
    resaleMarginBps: bigint;
    referralBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSentEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [to: string, amount: bigint, reason: string];
  export interface OutputObject {
    to: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SplitExecutedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    reseller: AddressLike,
    vendor: AddressLike,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    reseller: string,
    vendor: string,
    totalAmount: bigint
  ];
  export interface OutputObject {
    orderId: string;
    reseller: string;
    vendor: string;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SplitPayout extends BaseContract {
  connect(runner?: ContractRunner | null): SplitPayout;
  waitForDeployment(): Promise<this>;

  interface: SplitPayoutInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  escrowContract: TypedContractMethod<[], [string], "view">;

  getSplit: TypedContractMethod<
    [orderId: BytesLike],
    [SplitPayout.SplitStructOutput],
    "view"
  >;

  maxReferralDepth: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  referralBps: TypedContractMethod<[], [bigint], "view">;

  referralRegistry: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputation: TypedContractMethod<[], [string], "view">;

  resaleMarginBps: TypedContractMethod<[], [bigint], "view">;

  setConfig: TypedContractMethod<
    [
      _resaleMarginBps: BigNumberish,
      _referralBps: BigNumberish,
      _maxReferralDepth: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setEscrowContract: TypedContractMethod<
    [_escrow: AddressLike],
    [void],
    "nonpayable"
  >;

  split: TypedContractMethod<
    [
      orderId: BytesLike,
      amount: BigNumberish,
      reseller: AddressLike,
      vendor: AddressLike
    ],
    [void],
    "payable"
  >;

  splits: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        reseller: string;
        vendor: string;
        amount: bigint;
        resalePayout: bigint;
        vendorPayout: bigint;
        treasuryPayout: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "escrowContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSplit"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [SplitPayout.SplitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxReferralDepth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referralBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "referralRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resaleMarginBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setConfig"
  ): TypedContractMethod<
    [
      _resaleMarginBps: BigNumberish,
      _referralBps: BigNumberish,
      _maxReferralDepth: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEscrowContract"
  ): TypedContractMethod<[_escrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "split"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      amount: BigNumberish,
      reseller: AddressLike,
      vendor: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "splits"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean] & {
        reseller: string;
        vendor: string;
        amount: bigint;
        resalePayout: bigint;
        vendorPayout: bigint;
        treasuryPayout: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSent"
  ): TypedContractEvent<
    PaymentSentEvent.InputTuple,
    PaymentSentEvent.OutputTuple,
    PaymentSentEvent.OutputObject
  >;
  getEvent(
    key: "SplitExecuted"
  ): TypedContractEvent<
    SplitExecutedEvent.InputTuple,
    SplitExecutedEvent.OutputTuple,
    SplitExecutedEvent.OutputObject
  >;

  filters: {
    "ConfigUpdated(uint256,uint256)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentSent(address,uint256,string)": TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;
    PaymentSent: TypedContractEvent<
      PaymentSentEvent.InputTuple,
      PaymentSentEvent.OutputTuple,
      PaymentSentEvent.OutputObject
    >;

    "SplitExecuted(bytes32,address,address,uint256)": TypedContractEvent<
      SplitExecutedEvent.InputTuple,
      SplitExecutedEvent.OutputTuple,
      SplitExecutedEvent.OutputObject
    >;
    SplitExecuted: TypedContractEvent<
      SplitExecutedEvent.InputTuple,
      SplitExecutedEvent.OutputTuple,
      SplitExecutedEvent.OutputObject
    >;
  };
}
